# Generated by Django 3.0.2 on 2020-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.CharField(default='teachername', max_length=100),
        ),
    ]
