# Generated by Django 3.0.2 on 2020-08-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBTS_APP', '0002_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CompositeObjective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.PositiveIntegerField(verbose_name=0)),
                ('topic1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='CBTS_APP.Topic')),
                ('topic2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic2', to='CBTS_APP.Topic')),
            ],
        ),
    ]
